# Franklin Sheldon Plugin Configuration
# Sheldon: Fast, configurable shell plugin manager
# https://sheldon.cli.rs

shell = "zsh"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.ohmyzsh-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.ohmyzsh-history-substring-search]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/history-substring-search"

[plugins.ohmyzsh-colored-man-pages]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/colored-man-pages"

[plugins.ohmyzsh-command-not-found]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/command-not-found"
